### ISSUE TITLE
Release version 0.15 to PyPI

### ISSUE THREAD

**Issue by tykeal** [gabe565/pyruckus#5]
Home Assistant consumes pyruckus for it's integration to use Ruckus Unleashed devices. The latest version of Home Assistant (2022.7) that released on July 6, 2022 now fails to connect due to the underlying container now needing the fix that was put in place with commit 95d8ae06a36f686fa43a18994e2adceed28969a9

I did see that you bumped the release version, but PyPi doesn't have the new version yet. I expect that it will need to be on PyPI before Home Assistant can pick up the new version.

**Comment by gabe565** [comment]
Thank you, I have released [0.15](https://github.com/gabe565/pyruckus/releases/tag/0.15) of this package. I will submit a PR to Home Assistant, but do not have access to a Ruckus device right now, so I cannot test the new version. I may need some help testing the PR once it has been created!

Related: home-assistant/core#74540

**Comment by gabe565** [comment]
home-assistant/core#75032 has been merged in. Ruckus support will be fixed in 2022.7.4!
